export enum PacketType {
  UpdateServerInfo = 0,
  GenerateMap = 1,
  AddPlayer = 2,
  MovePlayer = 3,
  PlayerConnectionRequest = 4,
  PlayerDisconnectionNotification = 5,
  Ping = 6,
  Pong = 7,
  ServerClosed = 8,
  CastSkill = 9,
  SpawnItem = 10,
  SavePlayer = 11,
  ServerFull = 12,
  AxiomaticStatus = 13,
  AssetList = 14,
  UnknownPacketType = 666,
}
